### ISSUE TITLE
我使用docker跑的时候报错了

### ISSUE THREAD

**Issue by wripz** [WackyGem/Nicol#2]
<img width="1074" alt="微信图片_20240229101747" src="https://github.com/WackyGem/Nicol/assets/5949695/29f136cc-7acc-44ba-8c82-e58f4999965f">

**Comment by WackyGem** [comment]
> <img alt="微信图片_20240229101747" width="1074" src="https://private-user-images.githubusercontent.com/5949695/308772585-29f136cc-7acc-44ba-8c82-e58f4999965f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNzE2NTksIm5iZiI6MTcwOTI3MTM1OSwicGF0aCI6Ii81OTQ5Njk1LzMwODc3MjU4NS0yOWYxMzZjYy03YWNjLTQ0YmEtOGM4Mi1lNThmNDk5OTk2NWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDFUMDUzNTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTJjYzllODRmNDRkNjRhMzYxZWZlNzViMzg4Y2VkMGMxMDBiNzgwODBhZjVkYzQxNDU3MDQ1NDc2NmVlYjQ2NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xxOCrKGuviiP-0m97iRQlZVOdo_yNDztJ2Dw7rw7Ngw">

1. 可能是由于使用的docker-compose版本不兼容，建议升级docker-compose版本
2. 如果升级版本后仍然报相同的错误，建议尝试 `docker compose up`, 注意 docker 和 compose 之间没有-
